name: Build Android APK (BTR)

on:
  push:
    branches:
      - feat/btr-integration
  workflow_dispatch:

jobs:
  android:
    name: Build Android arm64-v8a APK
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: 代码迁出
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 构建Java环境
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"
          cache-dependency-path: |
            android/*.gradle*
            android/**/gradle-wrapper.properties

      - name: 安装Flutter
        uses: subosito/flutter-action@v2
        id: flutter-action
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Apply Patch
        shell: pwsh
        run: lib/scripts/patch.ps1 android

      - name: Set and Extract version
        shell: pwsh
        run: lib/scripts/build.ps1 android

      - name: Setup Permanent Release Keystore
        shell: bash
        run: |
          cat << 'EOF' | base64 -d > android/app/key.jks
          MIIKaAIBAzCCChIGCSqGSIb3DQEHAaCCCgMEggn/MIIJ+zCCBbIGCSqGSIb3DQEHAaCCBaMEggWfMIIFmzCCBZcGCyqGSIb3DQEMCgECoIIFQDCCBTwwZgYJKoZIhvcNAQUNMFkwOAYJKoZIhvcNAQUMMCsEFIucq0EWA1mHDbqs1e8GesW2nfIfAgInEAIBIDAMBggqhkiG9w0CCQUAMB0GCWCGSAFlAwQBKgQQ0ruE1hKIXbJrYgdi1kbxtgSCBNApedq42ydRebmA6ri4dNfi+NRroEQYArMjkcqtMrJe8RqyZnqaXxPQnoM533ViHsVKgn4weN5AzxXiTerkSCHizFPNF1uGCseF6uyYj2rdvzn377QHqDwgnk7m8f5PNJDhgEwcY9Ra48alN/zlGjrIgvS+x36V6Ut+DVbb4tc2UjhVGocQNWO+lVE+PUntSmZJnuvGIpCUpBQuIqu3c1ZZHbdmMdVwvk0RwG9muxvlxAlPfZGnXVOfJI2u7VOKxyKpmHH6Z8v1pkV3jEgUV6jJLPVmkaQIT2voZZtWoiz5cO8Ys4ZemlyjwuX+tpMFfuBkTKsNQzCUYkVVTqmP1g2VHULGoz1g3+BuH3XHRqQ8f5Qu3eckJ7p5lDuAn9UQBxsvH3Bmhz9DaWtJeBzEHuG+TsQghpeYYzVlXgPFX7lNm0hl8mN9bOEgi56nwrw8X8RiQv7Fo59mM3dugj1sfDRVEOP+WosY9MC2rfleVhBUkHEf5OtEO3JlPcmsRbajpaaB7j/YiQSROLVf1YRC2VwHUhGPAxaoXEjKiXj0IoKtgifPrEFKPacEUcfVyeHaj6BLJXWhCr9hRjpPXBMITWHsIcZJUjhsGXu2swGeF35EUdJWqoMEfN3PIgL/TsFcNihPA21SNgpgjUuflOrT80HHqN5QTJnqYtoDfU4Brc3QMOXQWnSi2858KLGz+oubhRqbc7l21K6DCZBrqbqGd97nRDinmelZi9HlrB89yJJT/ULxr/lZSPEYgrCASQxmX0deH7p6GU7X4otSteevRRtvr+yM8+36SC2IVbKdr/3jRJ8cw/hOmGIsezHzPNI/9s+reTLlL7nrp599hknCvxjGUwdiKEa4/S3gIEyvtdw2+R4Z1mIAmvHavUjH7c/9LSe/4eBKfEc68XZagEKiJWqfLX51y/tmMDK1y5PKpnStSw/SJyXSbAWYTYTmd1nRv8dLrpEpR7a/KA0vJxi2O5TgiJKtBvAKwlUn76mSTxIEpkzGcXWwBXO+CI8QYC6ej67SfamERjQXl26zYrbdJx9smT9pPGJqu6hA3wQ91S+KWjAZASx0VQKE4eLwhU+6/LG1t/ZNeLSTT02RIJJokA8uZZQrPAlDPzcc2EiAIIMl4yUICBr+KjHR28UGOUnqxY086inv4X8C1+J5cnoMl0wRVuN1PdwRA8HlWrr4kUQhmRZgcPWnOxxTPMc0hFcxTlR7Nor7xhVu6Oot7hiAUJ3rGxATMgQmyQwcVnIjB5sDxp7dGBZaYPjGSgB9ky/UkVGpPAw50puaPsmxRTCkxtBGAhWONfFuIUCErHocDPt9DOq0EmBimzrqSMXV1db1rN56vjW/lF6Kg8OU6r7mWh4/rDBzbJF2ZGKBwVPCmoOXLz+nYg0gcwyOd0Ak+0mhUS9dTyTBcY0On2FKSDF6wPRaXSxJxPc+p82VhrtrmX8Vx13HMIyClhqx+ILvTeWONj0eG1yw1jRzPDP9j6oT5TxssH3Htya1V7eMatLOMSCmpuX1HKtJ1ki0vb0lU/EIrsFAdOKD9rkrl+LRiP3RLrToLdDBfvnpDtg2ZhpVk+TfxpnPdV+2HLXJEvcYT5PIoIilJTGJCVWLVgPZiNi7KNlqHeNcQ2w1Mqde26uEXua21jFEMB8GCSqGSIb3DQEJFDESHhAAcABpAGwAaQBwAGwAdQBzMCEGCSqGSIb3DQEJFTEUBBJUaW1lIDE3OTA1NDEzMDgyODIwggRBBgkqhkiG9w0BBwagggQyMIIELgIBADCCBCcGCSqGSIb3DQEHATBmBgkqhkiG9w0BBQ0wWTA4BgkqhkiG9w0BBQwwKwQUY0iwyZdxg4t6NafSNJSLNtKfKIcCAicQAgEgMAwGCCqGSIb3DQIJBQAwHQYJYIZIAWUDBAEqBBB4sUYeCNRu3DEl8yLkW25xgIIDsN6BoV7Zo2rCmwfrpFGwaUTmySQtxEQSIgNlokEs4fbGTeMHD6sONC2DSDaqOGw6/mGaZ1jzZ+wfCAMCcX9N9p0GN8lRQWoEnokU/eAdAIqUw6K2mCm9fL2ySSKI4lhBpYqMgXu4sFnnDdMyGWgDZgmjquppUzPxtkHdBCiTNVQ9PdeKU9W46EcmTuy5oHehQuB4pr2rdtvquU+fn7iSCbYp08u8VkyeSaRanc9NaIqvdqbL09Bb29xOfCnK1o6i+ltuqYF/vIx4530CMonnDXnlKFC6YQ3/VvtEMvIs+xmTLe2wF7v9OHKNyYAL8snjIG8VXWHEXUU+WV6xbvxuaeadntnRU1duyLxZ3/8zoF7SRVGof9z6F1LOQ0aGpLCIbWBI2HtwHWPKjstMmG6qNFINn0wg+qdqpM5CLz9NGkbfLU9fFKCoYgeQV6WVkK/bPDNbNXJwgl89Imy/9uOGH4zcjLULdpagMXAjNahJVFEn/OoFYCwnpq/xyV9TwAtWkWak17FYnsEgYK+DjAfEaA7HtzkRb52vwF6YIn1848D/HbA9El5i1iAPVRgphsB+fygPkptaP29ELITaOywtr5YzbWFUXXe1PM76BBIzhkax3SqxmpTFK7Rl1iuepQkMb/huELhg8GRI01vV9+YT7DBwST+SwNoSJbsWoclT1Dz6pCcQ+z2/vQRb52KJFn5pVqABw66cJNkzLOkoMFpcro5cSpX6tMerAsCHm61dYQxRIZTxI+n5cfFI1/Qh0D/v46OED9tbN2dhEqEbQu8zSpVNFQmryM1L8ZSZ0mYg7RrRMkh9ONMaBoy2+ESIrS8QRhvD7C1aKAviwV8+HXtvLw76MdznB8aWi0G1eNeCdb8KfWprrXL3sUCtuI65W9bVUmkIcSWf6xJe0lOYvNIlMNrD413hWKqRf+p2x7FQz9DsY7KnNdozGbUJYVvhaXVqNQGS0tpZI2tz52IXQhEox7wf4aAOKXbEqv/D20OULlfHIa4lG8RsFWBOAZStG5qQliLlpY/G5jGpfExAY0GP3xROQSA+Ohv5M7U3Fs5id4xhfKrByZNInJpq3Ds+M8ebrfBWdc2sAXwbMgpNej8WNJMhZJNlp/lAB/yVBTnHZaDQe6UHUJih8XN9Hr9E9N0M9VA5jD7wSQExCW7onOAEjgKTqVCU8TVvuZCZun+JmY/BwSNswqakrk5gBw+/QbB+CX1wP+6FKSJxlFXBtWGYOr2mKkinoCiCYqvDakqxKJNJME0wMTANBglghkgBZQMEAgEFAAQgk6Tb3FbM8bMWGRNdKXFrGWuWmc7gjPbiZgtHP/Iw6NUEFJ+AXmgymuCQsGHkCdgEto2L6H9VAgInEA==
          EOF
          cat << 'EOF' > android/key.properties
          storeFile=key.jks
          storePassword=piliplus_btr_2026
          keyAlias=piliplus
          keyPassword=piliplus_btr_2026
          EOF

      - name: Flutter Build Release Apk
        run: flutter build apk --release --split-per-abi --dart-define-from-file=pili_release.json --no-pub

      - name: Rename APK
        shell: bash
        run: |
          for file in build/app/outputs/flutter-apk/app-*-release.apk; do
            abi=$(echo "$file" | sed -E 's|.*app-(.*)-release\.apk|\1|')
            mv "$file" "PiliPlus_android_${{ env.version }}_${abi}.apk"
          done

      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v4
        with:
          name: Android_arm64-v8a
          path: PiliPlus_android_*_arm64-v8a.apk

      - name: Upload all ABIs
        uses: actions/upload-artifact@v4
        with:
          name: Android_all_APKs
          path: PiliPlus_android_*.apk
